// styles/connectStyles.ts
import { StyleSheet, Platform } from "react-native";

export const colors = {
  backgroundDark: "#0d0d0d",
  backgroundMid: "#1a1a1a",
  border: "#ffd21f",
  textPrimary: "#ffffff",
  textSecondary: "#ccc",
  textMuted: "#cfcfcf",
  placeholderText: "#a0a0a0",
  accent: "#ffd21f",
  danger: "#ff4d4f",
  success: "#4CAF50",
  link: "#2e78b7",
  translucentLight: "rgba(255,255,255,0.06)",
  translucentBorder: "rgba(255,255,255,0.12)",
  badgeBg: "rgba(255,210,31,0.15)",
  modalBackdrop: "rgba(0,0,0,0.6)",
};

const webPad = Platform.select({ web: 24, default: 16 }) as number;

export const connectStyles = StyleSheet.create({
// connect.tsx
  container: {
    flex: 1,
    backgroundColor: colors.backgroundMid,
    paddingHorizontal: webPad,
    paddingTop: Platform.OS === "web" ? 12 : 8,
    paddingBottom: 8,
  },
  groupsListScroll: {
    flex: 1,
    // marginTop: 8,
  },
  // groupsListContent: {
  //   paddingBottom: 80,
  // },
  groupCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    marginBottom: 12,
    paddingHorizontal: 0,
    overflow: "hidden",
  },
  groupCardHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  groupCardTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
  },
  headerSmallFab: {
    backgroundColor: colors.accent,
    width: 26,
    height: 26,
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  headerSmallFabText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "900",
    marginTop: -1,
  },
  sectionHeader: {
    color: "#fff",
    fontSize: 28,
    textAlign: 'center',
    fontWeight: "700",
    marginBottom: 12,
    marginLeft: 4,
  },
  matchCard: {
    backgroundColor: "#1f1f1f",
    padding: 12,
    borderRadius: 12,
    // borderWidth: 1,
    // borderColor: colors.accent,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  matchLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  matchAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  matchAvatarFallback: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#333",
    alignItems: "center",
    justifyContent: "center",
  },
  matchAvatarInitial: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "700",
  },
  matchName: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 2,
  },
  matchTier: {
    color: "#FFD21F",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 2,
  },
  matchSubtitle: {
    color: "#bbb",
    fontSize: 14,
  },
  fab: {
    position: "absolute",
    right: 18,
    bottom: 18,
    width: 64,
    height: 64,
    borderRadius: 9999,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
  },
  fabPlus: {
    fontSize: 32,
    fontWeight: "900",
    color: "#000",
  }, 
// createGroupModal.tsx 
  modalBackdrop: {
    flex: 1,
    backgroundColor: colors.modalBackdrop,
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    alignSelf: "center",
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: 360,
    borderRadius: 16,
    padding: 16,
    backgroundColor: colors.backgroundDark,
    borderWidth: 2,
    borderColor: colors.border,
  },
  modalTitle: {
    color: colors.accent,
    fontSize: 24,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 10,
  },
  input: {
    height: 48,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.backgroundMid,
    color: "#ffffff",
    marginTop: 16,
    marginBottom: 12,
    fontSize: 18,
  },
  dropdownContainer: {
    position: "relative",
    width: "100%",
    zIndex: 2000,
  },  
  dropdownButton: {
    height: 48,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 8,
    backgroundColor: colors.backgroundMid,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  dropdownValue: {
    fontSize: 18,
    color: colors.textPrimary,
    flex: 1,
  },
  dropdownPlaceholder: {
    color: colors.placeholderText,
  },
  dropdownPanel: {
    position: "absolute",
    top: 48,
    left: 0,
    right: 0,
    backgroundColor: colors.backgroundMid,
    maxHeight: 220,
    borderRadius: 6,
    zIndex: 9999,
    elevation: 20,
    overflow: "hidden",
  },
  dropdownList: {
    flex: 1,
  },
  userRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 6,   
  },
  userName: {
    color: colors.textPrimary,
    fontSize: 16,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 16,
    justifyContent: "center",
    marginTop: 20,
  },
  button: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonGhost: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: colors.accent,
  },
  buttonGhostText: {
    color: colors.accent,
    fontSize: 18,
    fontWeight: "600",
  },
  buttonPrimary: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.accent,
  },
  buttonText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "600",
  },  
// groupChat.tsx & directMessageChat.tsx
  messagesList: {
    flex: 1,
  },
  dayHeaderWrapper: {
    flexDirection: "row",
    alignItems: "center",
    // marginVertical: 20,
  },
  dayHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#333",
  },
  dayHeaderText: {
    marginHorizontal: 12,
    color: "#ccc",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "#0f0f0f",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#222",
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  avatarWrapper: {
    marginRight: 12,
    marginTop: 6,
  },
  messageAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#333",
  },
  messageAvatarFallback: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#555",
    justifyContent: "center",
    alignItems: "center",
  },
  fallbackText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  messageContentBlock: {
    flexShrink: 1,
    paddingTop: 4,
  },
  messageSender: {
    color: "#ccc",
    fontSize: 12,
    marginBottom: 3,
  },   
  slackMessageText: {
    color: "#ddd",
    fontSize: 16,
    lineHeight: 20,
  },
  messageTimestamp: {
    color: "#888",
    fontSize: 11,
    marginTop: 4,
    alignSelf: "flex-start",
  },
  messageInputRow: {
    flexDirection: "row",
    marginTop: 12,
    marginBottom: Platform.OS === "ios" ? 28 : 20,
  },
  messageInput: {
    flex: 1,
    backgroundColor: colors.translucentLight,
    color: colors.textPrimary,
    padding: 10,
    borderRadius: 8,
  },
  sendButton: {
    marginLeft: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: colors.accent,
    borderRadius: 8,
  },
  sendButtonText: {
    color: "#000",
    fontWeight: "700",
  },
});
