// styles/profileStyles.ts
import { Platform, StyleSheet } from "react-native";

export const colors = {
  backgroundDark: "#0d0d0d",
  backgroundMid: "#1a1a1a",
  textPrimary: "#ffffff",
  textSecondary: "#ccc",
  textMuted: "#cfcfcf",
  placeholderText: "#a0a0a0",
  accent: "#ffd21f",
  danger: "#ff4d4f",
  translucentLight: "rgba(255,255,255,0.06)",
  translucentBorder: "rgba(255,255,255,0.12)",
  badgeBg: "rgba(255,210,31,0.15)",
  modalBackdrop: "rgba(0,0,0,0.6)",
};

const webPad = Platform.select({ web: 24, default: 16 }) as number;

export const profileStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.backgroundMid,
    alignItems: "center",
    paddingHorizontal: webPad,
    paddingTop: Platform.OS === "web" ? 20 : 16,
    paddingBottom: 100,
  },
  center: {
    alignItems: "center",
    justifyContent: "center",
  },
  muted: {
    color: colors.textSecondary,
    fontSize: 24,
  },
  profileContainer: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 2,
    // borderColor: colors.accent,
    borderColor: colors.translucentBorder,
    padding: 16,
    backgroundColor: colors.backgroundMid,
  },
  header: {
    flexDirection: Platform.OS === "web" ? "row" : "column",
    alignItems: Platform.OS === "web" ? "flex-start" : "center",
    justifyContent: "flex-start",
    gap: 16,
  },
  infoSection: {
    flex: 1,
    alignItems: Platform.OS === "web" ? "flex-start" : "center",
    justifyContent: "center",
    textAlign: Platform.OS === "web" ? "left" : "center",
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  nameColumn: {
    flex: 1,
    justifyContent: "center",
  },
  avatarLeft: {
    alignItems: "center",
    justifyContent: "center",
  },
  editTopRightBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 10,
    elevation: 10,
    borderRadius: 9999,
    // backgroundColor: colors.translucentLight,
    backgroundColor: colors.accent,
    // borderWidth: 1,
    // borderColor: colors.translucentBorder,
    padding: 16,
    ...(Platform.OS === "web" && { cursor: "pointer" }),
  },
  title: {
    color: colors.textPrimary,
    fontSize: Platform.OS === "web" ? 36 : 32,
    fontWeight: "600",
    marginTop: Platform.OS === "web" ? 4 : 0,
  },
  subtitle: {
    color: colors.accent,
    fontSize: Platform.OS === "web" ? 24 : 20,
    fontWeight: "600",
    marginBottom: Platform.OS === "web" ? 12 : 0,
  },  
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: 4,
  },
  badgeRowMobile: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  profileDetailsSection: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
  },
  profileDetailBlock: {
    marginBottom: 12,
  },
  profileDetailLabel: {
    color: "#a0a0a0",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  profileDetailText: {
    color: "#fff",
    fontSize: 16,
    lineHeight: 22,
  },  
  roleBadge: {
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignSelf: "flex-start",
  },
  roleBadgeText: {
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 0.2,
    textTransform: "capitalize",
  }, 
  avatarContainerClickable: {
    ...(Platform.OS === "web" && { cursor: "pointer" }),
  },
  avatarOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === "web" ? "25%" : "30%",
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarOverlayText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "600",
  },
  avatarContainer: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 9999,
    width: 150,
    height: 150,
    borderWidth: 1,
    borderColor: colors.translucentBorder,
    backgroundColor: colors.translucentLight,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 9999,
  },
  avatarLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 9999,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  pictureModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.modalBackdrop,
  },
  pictureModalCard: {
    alignSelf: "center",
    width: "90%",
    maxWidth: 500,
    borderRadius: 16,
    padding: 20,
    backgroundColor: colors.backgroundDark,
    borderWidth: 2,
    borderColor: colors.accent,
  },
  previewImage: {
    width: 200,
    height: 200,
    borderRadius: 130,
    alignSelf: "center",
    marginBottom: 12,
  },
  avatarWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.translucentLight,
  },
  avatarPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    fontSize: 32,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  label: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  input: {
    height: 48,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.backgroundMid,
    color: "#ffffff",
    marginTop: 16,
    marginBottom: 12,
    fontSize: 18,
  },  
  modalLabel: {
    color: "#a0a0a0",
    fontSize: 14,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 8,
    marginBottom: 8,
  },  
  dropdownContainer: {
    width: "100%",
  },
  dropdownButton: {
    height: 48,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 8,
    backgroundColor: colors.backgroundMid,
    color: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownValue: {
    fontSize: 18,
    color: colors.textPrimary,
    flex: 1,
  },
  dropdownPlaceholder: {
    color: colors.placeholderText,
  },
  dropdownModal: {
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  dropdownList: {
    width: "80%",
    maxWidth: 300,
    minHeight: 485,
    backgroundColor: colors.backgroundMid,
    borderRadius: 16,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  dropdownItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.translucentBorder,
  },
  dropdownItemLast: {
    borderBottomWidth: 0,
  },
  dropdownItemText: {
    fontSize: 16,
    color: colors.textPrimary,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 16,
    justifyContent: "center",
    marginTop: 20,
  },
  button: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimary: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.accent,
  },
  buttonText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "600",
  },  
  buttonGhost: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: colors.accent,
  },
  buttonGhostText: {
    color: colors.accent,
    fontSize: 18,
    fontWeight: "600",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.modalBackdrop,
  },
  modalCardWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 16,
  },  
  modalCard: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 360,
    borderRadius: 16,
    padding: 16,
    backgroundColor: colors.backgroundDark,
    borderWidth: 2,
    borderColor: colors.accent,
  },
  modalTitle: {
    color: colors.accent,
    fontSize: 24,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 10,
  },

  // === CROPPER ===
  cropperContainer: {
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 16,
    position: "relative",
  },
  cropperInstruction: {
    textAlign: "center",
    marginTop: 16,
    marginBottom: 16,
    color: colors.textSecondary,
    fontSize: 24,
  },
  cropperCircleWrap: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 9999,
    overflow: "hidden",
    backgroundColor: colors.backgroundDark,
    alignSelf: "center",
    justifyContent: "center",
    marginBottom: 20,
  },  
  // Dropdowns
  dropdownFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#333",
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  dropdownFooterButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    paddingVertical: 10,
  },
  dropdownFooterClear: {
    borderWidth: 1,
    borderColor: "#555",
    marginRight: 8,
  },
  dropdownFooterDone: {
    backgroundColor: colors.accent,
    marginLeft: 8,
  },
  dropdownFooterClearText: {
    color: "#ccc",
    fontSize: 16,
    fontWeight: "500",
  },
  dropdownFooterDoneText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "700",
  },
  dropdownItemSelected: {
    backgroundColor: colors.translucentLight,
  },
  dropdownItemTextSelected: {
    color: colors.accent,
    fontWeight: "600",
  },
});
